// <auto-generated />
namespace GameTrader.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedusernamesinceitbrokestuffandiwasntthinkingwheniaddedit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedusernamesinceitbrokestuffandiwasntthinkingwheniaddedit));
        
        string IMigrationMetadata.Id
        {
            get { return "201507241752053_removed username since it broke stuff and i wasnt thinking when i added it"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
